version: 2
jobs:

  build-test-deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "pom.xml" }}
                - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run: mvn versions:set versions:commit -DnewVersion=1.$CIRCLE_BUILD_NUM.0
      - run: docker login -u $DOCKER_MB_USER -p $DOCKER_MB_PASS
      - run: mvn install

      - store_test_results:
          path: test-results


workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build-test-deploy:
          context: mblackford-docker
