version: 2
jobs:
  run-tests:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run: mvn integration-test -DskipDocker
  package:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - run: docker login -u $DOCKER_MB_USER -p $DOCKER_MB_PASS
      - run: mvn package -DskipTests
workflows:
  version: 2
  build_and_test:
    jobs:
      - run-tests
      - package:
          context: mblackford-docker
