server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mattztech/super-secret-passwords.git
#          uri: git@github.com:mattztech/super-secret-passwords.git
#          uri: ${HOME}/dev/git/super-secret-passwords
